### ISSUE TITLE
Update documentation for merge-based bottling

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-developer#37]
We've been doing it long enough now that it's fairly well in place IMO, but I keep forgetting how to do it because the only place it's documented is in Slack.

(Of course, being out of action as a maintainer for the past month-and-a-half doesn't help either!)

**Comment by maxim-belkin** [comment]
create and checkout a new branch
brew merge-homebrew --core
...

**Comment by rwhogg** [comment]
Sorry, I meant that the last part, where you pull the bottles directly from a merge PR without individual `build-bottle-pr` invocations, is the part that I get lost about.

**Comment by maxim-belkin** [comment]
I believe it's `brew pull --bottle <merge-PR-url>` in a master branch

**Comment by sjackman** [comment]
Yep, and use `--clean` as well so as not to modify the commit message, which adds all the log messages of the commits below the merge to the merge commit.
`brew pull --bottle --clean <merge-PR-url>`
`brew pull` should be modified to imply `--clean` when pulling a merge PR.

The biggest reason for building bottles of a merge PR to fail is that one formula times out or exceeds memory the 4 GB memory limit of CircleCI. I think we should modify those formula that are known to timeout or exceed memory to bail early, so they don't ruin the whole CI run. Something like
```
bottle :disabled if ENV["CIRCLECI"]
```

**Comment by issyl0** [comment]
The `brew pull --bottle` step is now [documented](https://docs.brew.sh/Homebrew-linuxbrew-core-Maintainer-Guide#pulling-bottles) for future maintainers.

**Comment by sjackman** [comment]
This issue referred to documenting a merge-based strategy of bottling. It involved opening a merge PR, building the bottles in that PR, and then pushing that PR along with the bottles built by it to `master` in one atomic push. There's challenges to getting this workflow working, but it would in my opinion improve the user-facing quality of Linuxbrew-core by avoiding the period where formulae are unbottled.

**Comment by issyl0** [comment]
Oh, interesting. I misunderstood, sorry. :flushed: This seems to be in the same ballpark an ongoing discussion in [a recently opened issue in Homebrew/linuxbrew-core](https://github.com/Homebrew/linuxbrew-core/issues/15766) about reducing the amount of bottle-less time that users have. I suggest we move conversation over there, as that's the relevant repo these days. Does that sound good?

**Comment by sjackman** [comment]
Moved to https://github.com/Homebrew/linuxbrew-core/issues/15766
