### ISSUE TITLE
merge-homebrew: Provide way to not open editor 

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-developer#43]
I personally don't like resolving merge conflicts in a standard editor and rely entirely on a dedicated mergetool (like `meld` or `diffuse`).

I don't have time to do this myself at the moment, but as I suspect I'm the only one who cares strongly about this, I'll try to find time to do it when we're done addressing the science migrations.

**Comment by sjackman** [comment]
I believe you can modify your git configuration to accomplish this.
```
git config --global merge.tool
```
See *External Merge and Diff Tools* in https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by rwhogg** [comment]
I have `merge.tool` set in my Git config (to `meld` on my personal laptop); the issue is rather that `which_editor` is called from `merge-homebrew` and the resulting editor is then invoked on the conflicting files without, as far as I can see, I way to disable it.
